### ISSUE TITLE
Is it possible to create an flip-effect?

### ISSUE THREAD

**Issue by PanicMan** [ygalanter/EffectLayer#11]
Hello, is it possible to create an flip effect?
Like here, where the Clock flips down: https://www.youtube.com/watch?v=BnIGFSSa1PE
Maybe in the Parameters, how many steps and on what step we are right now...

**Comment by ygalanter** [comment]
There is a separate library for that called by another dev called FlipLayer, I used it in my Big Flip Clock watchface https://github.com/ygalanter/BIG_FLIP_CLOCK you can see it in action by installing http://apps.getpebble.com/en_US/application/53a9f0fa6b1a978507000083

**Comment by PanicMan** [comment]
Hello!

Thanks for your reply!

I already saw that clock, nice work!
But that lib don't work on Basalt, isn't it so?

Greetings
Jack

2015-05-29 12:15 GMT+02:00 ygalanter <notifications@github.com>:

**Comment by ygalanter** [comment]
Yup, the only time I tried it in SDK 3 - it failed, this is why I keep it SDK 2 for now (which technically works on Basalt). You may want to contact Gregoire Sage, he's the author of the library (https://github.com/gregoiresage/pebble-gbitmap-lib) and incidentally also one of the contributors to EffectLayer

**Comment by ygalanter** [comment]
Just got notified by Bitmap library author that it has been updated for Basalt.

**Comment by PanicMan** [comment]
Yes, he already told me, thanks!

2015-06-03 0:06 GMT+02:00 ygalanter <notifications@github.com>:
