### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by edwinfinch** [ygalanter/EffectLayer#6]
This is an awesome library. I'm playing around with it now. But there's barely any documentation aside from your personal blog and some comments that don't help too much. Are there plans for documentation of it?

**Comment by ygalanter** [comment]
Sorry about that, we haven't forgotten, just didn't get to it yet, the library itself happened kinda spontaneously, we were just excited we found an extendable platform to which new effects can be added easily.
Hopefully I will be able to put something together this week, meanwhile if you have any questions, let me know!

P.S. Hey, I know you :) You're Lignite guy! Would be pretty cool to see the library used in the collection.

**Comment by edwinfinch** [comment]
Sweet, thanks. The comments are good but Github docs never hurt :)

And yes, I am! We're already implementing EffectLayer in Mosaic (which will be free, you've probably already seen photos of it) and plan on adding it into most or all of the faces in the collection. A killer feature is inverting since InverterLayer is depreciated after 2.x (I almost shed a tear).  Great job again on the library!

**Comment by ygalanter** [comment]
I think I will add a parameter to the Inverter effect to invert only black & white colors. Sometimes you want to keep other colors intact.
I backed your Kickstarter so I get regular updates and indeed saw mockups and photos, can't wait to play with real ones. It's pretty cool when designer and coder work as a team.

**Comment by ygalanter** [comment]
Ok mini-documentation is now in place.
